### ISSUE TITLE
Written feedback 

### ISSUE THREAD

**Issue by JosieAilsa** [jjgray90/js-calculator#1]
## Version Control:

- 15 meaningful commits are present - all with meaningful commit messages

## Site Output:

- Has complete features that go above and beyond the standard requirements, the audio on button clicks and the easter egg 🤩. This is such an awesome project JJ well done - can see you’ve really had fun with it!

## Readability:

- All variables and functions have meaningful names, there a no casing issues
- There is clear separation between all sections of code
- Complex conditions or logic are easily understood
- BEM is used correctly!

## Responsiveness

- Site works and excellent on mobile, tablet, and desktop screen sizes

## Code Knowledge and Use

- Functions have been used to break up your code, and I can see you have a really good grasp of DOM manipulation
- To improve think about using guard clauses or try to use parameters and return from some functions

**Comment by jjgray90** [comment]
Thanks for the positive feedback @JosieAilsa! 😄 Really enjoyed building this one.
